import { MigrationInterface, QueryRunner } from "typeorm";

export class AddClinicalModules1788575893045 implements MigrationInterface {
    name = 'AddClinicalModules1788575893045'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."inventory_items_type_enum" AS ENUM('medication', 'consumable', 'reagent', 'equipment', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_items_unitofmeasure_enum" AS ENUM('PCS', 'BOX', 'PACK', 'CARTON', 'ROLL', 'PAIR', 'SET', 'KG', 'LITRE', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "inventory_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" jsonb, "sku" character varying(64) NOT NULL, "name" character varying(150) NOT NULL, "description" text, "type" "public"."inventory_items_type_enum" NOT NULL DEFAULT 'consumable', "unitOfMeasure" "public"."inventory_items_unitofmeasure_enum" NOT NULL DEFAULT 'PCS', "minStockLevel" integer NOT NULL DEFAULT '0', "reorderLevel" integer NOT NULL DEFAULT '0', "unitPrice" integer NOT NULL DEFAULT '0', "manufacturer" character varying(100), "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_cf2f451407242e132547ac19169" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_395ec8d9e0cad6e3890b989fc1" ON "inventory_items"  ("sku") `);
        await queryRunner.query(`CREATE TYPE "public"."inventory_stores_type_enum" AS ENUM('GENERAL', 'DEPARTMENT')`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_stores_department_enum" AS ENUM('reception', 'triage', 'outpatient_clinic', 'inpatient_ward', 'main_laboratory', 'radiology', 'main_pharmacy', 'finance', 'administrator')`);
        await queryRunner.query(`CREATE TABLE "inventory_stores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" jsonb, "name" character varying(100) NOT NULL, "type" "public"."inventory_stores_type_enum" NOT NULL DEFAULT 'GENERAL', "department" "public"."inventory_stores_department_enum", "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_94ed4d5e004b7e0c5a376fd96ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d63922590c9af4ed22351b66a0" ON "inventory_stores"  ("name") `);
        await queryRunner.query(`CREATE TABLE "inventory_stock" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" jsonb, "storeId" uuid NOT NULL, "itemId" uuid NOT NULL, "quantity" integer NOT NULL DEFAULT '0', "lastRestockedAt" TIMESTAMP, CONSTRAINT "PK_a13d56d2087e6d9eb3d480395bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_987047a1579af60ce16f0aae4c" ON "inventory_stock"  ("storeId", "itemId") `);
        await queryRunner.query(`CREATE TYPE "public"."inventory_transactions_type_enum" AS ENUM('RECEIPT', 'ISSUE', 'TRANSFER_OUT', 'TRANSFER_IN', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'RETURN', 'DISPOSAL')`);
        await queryRunner.query(`CREATE TABLE "inventory_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" jsonb, "storeId" uuid NOT NULL, "itemId" uuid NOT NULL, "type" "public"."inventory_transactions_type_enum" NOT NULL, "quantity" integer NOT NULL, "runningBalance" integer NOT NULL, "counterpartStoreId" uuid, "referenceType" character varying(100), "referenceId" uuid, "performedById" uuid NOT NULL, "notes" text, CONSTRAINT "PK_9b7144851f08f9eededde7edd42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_77c504222900b8c55995423093" ON "inventory_transactions"  ("storeId", "itemId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."lab_tests_category_enum" AS ENUM('hematology', 'chemistry', 'microbiology', 'immunology', 'urinalysis', 'parasitology', 'radiology', 'histopathology', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."lab_tests_sampletype_enum" AS ENUM('blood', 'urine', 'stool', 'sputum', 'csf', 'tissue', 'swab', 'imaging', 'other')`);
        await queryRunner.query(`CREATE TABLE "lab_tests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" jsonb, "code" character varying(32) NOT NULL, "name" character varying(150) NOT NULL, "description" character varying(500), "category" "public"."lab_tests_category_enum" NOT NULL DEFAULT 'other', "sampleType" "public"."lab_tests_sampletype_enum" NOT NULL DEFAULT 'blood', "unit" character varying(32), "referenceRange" character varying(150), "price" integer NOT NULL DEFAULT '0', "turnaroundHours" integer, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_400d229da68540bf586c0f4a20f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b7756de508bcd61121c5aa28b5" ON "lab_tests"  ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."lab_order_items_status_enum" AS ENUM('pending', 'collected', 'in_process', 'result_ready', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "lab_order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" jsonb, "orderId" uuid NOT NULL, "testId" uuid NOT NULL, "status" "public"."lab_order_items_status_enum" NOT NULL DEFAULT 'pending', "resultValue" character varying(255), "resultNotes" text, "isAbnormal" boolean NOT NULL DEFAULT false, "resultedById" uuid, "collectedAt" TIMESTAMP, "resultedAt" TIMESTAMP, CONSTRAINT "PK_3447771b48b27a3882eb689b41d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1adfd1e514ddf567fc4dd044e2" ON "lab_order_items"  ("orderId", "testId") `);
        await queryRunner.query(`CREATE TYPE "public"."lab_orders_status_enum" AS ENUM('pending', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."lab_orders_priority_enum" AS ENUM('routine', 'urgent', 'stat')`);
        await queryRunner.query(`CREATE TABLE "lab_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" jsonb, "patientId" uuid NOT NULL, "consultationId" uuid, "visitId" uuid, "orderedById" uuid NOT NULL, "status" "public"."lab_orders_status_enum" NOT NULL DEFAULT 'pending', "priority" "public"."lab_orders_priority_enum" NOT NULL DEFAULT 'routine', "clinicalNotes" character varying(500), "completedAt" TIMESTAMP, CONSTRAINT "PK_a488d533e758e6ba02958198f1c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ee3d81aa3a690864a5a47e170a" ON "lab_orders"  ("patientId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('system', 'lab_result', 'lab_order', 'prescription', 'appointment', 'visit', 'queue', 'inventory', 'general')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('in_app', 'email', 'sms')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_priority_enum" AS ENUM('low', 'normal', 'high', 'critical')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('unread', 'read', 'archived')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" jsonb, "userId" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL DEFAULT 'general', "channel" "public"."notifications_channel_enum" NOT NULL DEFAULT 'in_app', "priority" "public"."notifications_priority_enum" NOT NULL DEFAULT 'normal', "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'unread', "title" character varying(200) NOT NULL, "body" text NOT NULL, "actionUrl" character varying(200), "resourceType" character varying(100), "resourceId" uuid, "readAt" TIMESTAMP, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_78207b2dc2b0d717649e89d3fc" ON "notifications"  ("userId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."prescriptions_status_enum" AS ENUM('pending', 'partially_dispensed', 'dispensed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "prescriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" jsonb, "patientId" uuid NOT NULL, "consultationId" uuid, "prescribedById" uuid NOT NULL, "status" "public"."prescriptions_status_enum" NOT NULL DEFAULT 'pending', "notes" text, CONSTRAINT "PK_097b2cc2f2b7e56825468188503" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5e949ee06efde0a8de34c39081" ON "prescriptions"  ("patientId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."prescription_items_status_enum" AS ENUM('pending', 'partial', 'dispensed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "prescription_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" jsonb, "prescriptionId" uuid NOT NULL, "itemId" uuid NOT NULL, "dosage" character varying(100) NOT NULL, "frequency" character varying(100) NOT NULL, "duration" character varying(100), "quantity" integer NOT NULL, "dispensedQuantity" integer NOT NULL DEFAULT '0', "status" "public"."prescription_items_status_enum" NOT NULL DEFAULT 'pending', "instructions" text, CONSTRAINT "PK_6216831f49afc381b3934c9672c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dispense_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" jsonb, "dispenseId" uuid NOT NULL, "prescriptionItemId" uuid NOT NULL, "quantity" integer NOT NULL, CONSTRAINT "PK_36f412442ceea88d3523112019a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dispenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" jsonb, "prescriptionId" uuid NOT NULL, "dispensedById" uuid NOT NULL, "storeId" uuid NOT NULL, "notes" text, CONSTRAINT "PK_335c04e2450c6503205c8f7ba3e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "inventory_stock" ADD CONSTRAINT "FK_55d8ae927532ae145362a5419ea" FOREIGN KEY ("storeId") REFERENCES "inventory_stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_stock" ADD CONSTRAINT "FK_c96bbf7243692ed474f2f1e7053" FOREIGN KEY ("itemId") REFERENCES "inventory_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_8d364f5ea41e31f2522fc32143d" FOREIGN KEY ("storeId") REFERENCES "inventory_stores"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_d027ed40e39e81b95d21a3e8c98" FOREIGN KEY ("itemId") REFERENCES "inventory_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_e05025de9088a169361a649b8b4" FOREIGN KEY ("counterpartStoreId") REFERENCES "inventory_stores"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_301376a26ebb63e47651ef6a817" FOREIGN KEY ("performedById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_order_items" ADD CONSTRAINT "FK_337ae120fdb06600788888373ac" FOREIGN KEY ("orderId") REFERENCES "lab_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_order_items" ADD CONSTRAINT "FK_02e79c2aaba3532c37d6a5e823b" FOREIGN KEY ("testId") REFERENCES "lab_tests"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_order_items" ADD CONSTRAINT "FK_6a1e33a7a361d3f8ee40da32495" FOREIGN KEY ("resultedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_orders" ADD CONSTRAINT "FK_d52719e08cd859eb66ccbd4177e" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_orders" ADD CONSTRAINT "FK_50db03f9c9a50315064be2ea1e3" FOREIGN KEY ("consultationId") REFERENCES "consultations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_orders" ADD CONSTRAINT "FK_48253a6f5093de853cbeb119391" FOREIGN KEY ("visitId") REFERENCES "visits"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_orders" ADD CONSTRAINT "FK_1990792a0e01ba9a5ff71026058" FOREIGN KEY ("orderedById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescriptions" ADD CONSTRAINT "FK_51f48335657278b20348dde416c" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescriptions" ADD CONSTRAINT "FK_29fe8d9d7fd15107817912ff604" FOREIGN KEY ("consultationId") REFERENCES "consultations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescriptions" ADD CONSTRAINT "FK_82376aad120d12ff8b7f19d7b70" FOREIGN KEY ("prescribedById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescription_items" ADD CONSTRAINT "FK_8f604306272f41c9be46cca4360" FOREIGN KEY ("prescriptionId") REFERENCES "prescriptions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescription_items" ADD CONSTRAINT "FK_4e265f5ba9de85ff9cf01857619" FOREIGN KEY ("itemId") REFERENCES "inventory_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispense_items" ADD CONSTRAINT "FK_763e8049d8d745a0b2b3638b2dc" FOREIGN KEY ("dispenseId") REFERENCES "dispenses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispense_items" ADD CONSTRAINT "FK_5906aeccb3fcc44115e290ad9f1" FOREIGN KEY ("prescriptionItemId") REFERENCES "prescription_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispenses" ADD CONSTRAINT "FK_98eaafe81fd0b06dc2d9338055b" FOREIGN KEY ("prescriptionId") REFERENCES "prescriptions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispenses" ADD CONSTRAINT "FK_ef59d4e988dd83c8a45919c3309" FOREIGN KEY ("dispensedById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispenses" ADD CONSTRAINT "FK_2554439c889b41a9e2da85e5324" FOREIGN KEY ("storeId") REFERENCES "inventory_stores"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "dispenses" DROP CONSTRAINT "FK_2554439c889b41a9e2da85e5324"`);
        await queryRunner.query(`ALTER TABLE "dispenses" DROP CONSTRAINT "FK_ef59d4e988dd83c8a45919c3309"`);
        await queryRunner.query(`ALTER TABLE "dispenses" DROP CONSTRAINT "FK_98eaafe81fd0b06dc2d9338055b"`);
        await queryRunner.query(`ALTER TABLE "dispense_items" DROP CONSTRAINT "FK_5906aeccb3fcc44115e290ad9f1"`);
        await queryRunner.query(`ALTER TABLE "dispense_items" DROP CONSTRAINT "FK_763e8049d8d745a0b2b3638b2dc"`);
        await queryRunner.query(`ALTER TABLE "prescription_items" DROP CONSTRAINT "FK_4e265f5ba9de85ff9cf01857619"`);
        await queryRunner.query(`ALTER TABLE "prescription_items" DROP CONSTRAINT "FK_8f604306272f41c9be46cca4360"`);
        await queryRunner.query(`ALTER TABLE "prescriptions" DROP CONSTRAINT "FK_82376aad120d12ff8b7f19d7b70"`);
        await queryRunner.query(`ALTER TABLE "prescriptions" DROP CONSTRAINT "FK_29fe8d9d7fd15107817912ff604"`);
        await queryRunner.query(`ALTER TABLE "prescriptions" DROP CONSTRAINT "FK_51f48335657278b20348dde416c"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "lab_orders" DROP CONSTRAINT "FK_1990792a0e01ba9a5ff71026058"`);
        await queryRunner.query(`ALTER TABLE "lab_orders" DROP CONSTRAINT "FK_48253a6f5093de853cbeb119391"`);
        await queryRunner.query(`ALTER TABLE "lab_orders" DROP CONSTRAINT "FK_50db03f9c9a50315064be2ea1e3"`);
        await queryRunner.query(`ALTER TABLE "lab_orders" DROP CONSTRAINT "FK_d52719e08cd859eb66ccbd4177e"`);
        await queryRunner.query(`ALTER TABLE "lab_order_items" DROP CONSTRAINT "FK_6a1e33a7a361d3f8ee40da32495"`);
        await queryRunner.query(`ALTER TABLE "lab_order_items" DROP CONSTRAINT "FK_02e79c2aaba3532c37d6a5e823b"`);
        await queryRunner.query(`ALTER TABLE "lab_order_items" DROP CONSTRAINT "FK_337ae120fdb06600788888373ac"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_301376a26ebb63e47651ef6a817"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_e05025de9088a169361a649b8b4"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_d027ed40e39e81b95d21a3e8c98"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_8d364f5ea41e31f2522fc32143d"`);
        await queryRunner.query(`ALTER TABLE "inventory_stock" DROP CONSTRAINT "FK_c96bbf7243692ed474f2f1e7053"`);
        await queryRunner.query(`ALTER TABLE "inventory_stock" DROP CONSTRAINT "FK_55d8ae927532ae145362a5419ea"`);
        await queryRunner.query(`DROP TABLE "dispenses"`);
        await queryRunner.query(`DROP TABLE "dispense_items"`);
        await queryRunner.query(`DROP TABLE "prescription_items"`);
        await queryRunner.query(`DROP TYPE "public"."prescription_items_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e949ee06efde0a8de34c39081"`);
        await queryRunner.query(`DROP TABLE "prescriptions"`);
        await queryRunner.query(`DROP TYPE "public"."prescriptions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78207b2dc2b0d717649e89d3fc"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee3d81aa3a690864a5a47e170a"`);
        await queryRunner.query(`DROP TABLE "lab_orders"`);
        await queryRunner.query(`DROP TYPE "public"."lab_orders_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."lab_orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1adfd1e514ddf567fc4dd044e2"`);
        await queryRunner.query(`DROP TABLE "lab_order_items"`);
        await queryRunner.query(`DROP TYPE "public"."lab_order_items_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7756de508bcd61121c5aa28b5"`);
        await queryRunner.query(`DROP TABLE "lab_tests"`);
        await queryRunner.query(`DROP TYPE "public"."lab_tests_sampletype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."lab_tests_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77c504222900b8c55995423093"`);
        await queryRunner.query(`DROP TABLE "inventory_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_987047a1579af60ce16f0aae4c"`);
        await queryRunner.query(`DROP TABLE "inventory_stock"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d63922590c9af4ed22351b66a0"`);
        await queryRunner.query(`DROP TABLE "inventory_stores"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_stores_department_enum"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_stores_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_395ec8d9e0cad6e3890b989fc1"`);
        await queryRunner.query(`DROP TABLE "inventory_items"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_items_unitofmeasure_enum"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_items_type_enum"`);
    }

}
