
export enum InventoryTransactionType {
  RECEIPT = "RECEIPT",
  ISSUE = "ISSUE", 
  TRANSFER_OUT = "TRANSFER_OUT", 
  TRANSFER_IN = "TRANSFER_IN", 
  ADJUSTMENT_IN = "ADJUSTMENT_IN", 
  ADJUSTMENT_OUT = "ADJUSTMENT_OUT",
  RETURN = "RETURN",
  DISPOSAL = "DISPOSAL", 
}