export enum Department {
  RECEPTION = 'RECEPTION',
  TRIAGE = 'TRIAGE',
  OUTPATIENT_CLINIC = 'OUTPATIENT_CLINIC',
  INPATIENT_WARD = 'INPATIENT_WARD',
  MAIN_LABORATORY = 'MAIN_LABORATORY',
  RADIOLOGY = 'RADIOLOGY',
  MAIN_PHARMACY = 'MAIN_PHARMACY',
  FINANCE = 'FINANCE',
  ADMINISTRATION = 'ADMINISTRATION',
}